name: Build APK with EAS

on:
  workflow_dispatch:

jobs:
  build:
    name: 🔧 Build APK
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 📦 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🧩 Install dependencies (with peer fix)
        run: npm install --legacy-peer-deps

      - name: 🛠 Install EAS CLI
        run: npm install -g eas-cli

      - name: 🔐 Login with Expo Token
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: 🚀 Build APK
        run: eas build --platform android --profile preview --non-interactive
